modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "huntersmarket"
version = "${version}"
displayName = "Hunter's Market"
description = '''Compete to earn 10,000 gold by mining and selling ores!'''
authors = "ksoichiro"
displayURL = "https://github.com/ksoichiro/HuntersMarket"

[[dependencies.huntersmarket]]
modId = "neoforge"
type = "required"
versionRange = "[21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.huntersmarket]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3,1.21.4)"
ordering = "NONE"
side = "BOTH"

[[dependencies.huntersmarket]]
modId = "architectury"
type = "required"
versionRange = "[14,)"
ordering = "AFTER"
side = "BOTH"
